extra check

diff --git a/.github/actions/remove-mock-release-and-tag/action.yml b/.github/actions/remove-mock-release-and-tag/action.yml
--- a/.github/actions/remove-mock-release-and-tag/action.yml
+++ b/.github/actions/remove-mock-release-and-tag/action.yml
@@ -23,15 +23,21 @@ runs:
       with:
         tag: ${{ inputs.version }}
 
-    - name: Delete tag if it exist
+    - name: Delete tag if it exist and ends with "-mock"
       if: steps.check-tag.outputs.exists == 'true'
       shell: bash
       env:
         GITHUB_TOKEN: ${{ inputs.gh-token }}
         VERSION: ${{ inputs.version }}
       run: |
-        echo "Removing '${VERSION}' tag from: ${REPO}"
-        git push origin --delete ${VERSION}
+        if [[ "${VERSION}" == *-mock ]]; then
+          echo "Removing '${VERSION}' tag from: ${REPO}"
+          git push origin --delete ${VERSION}
+        else
+          echo "version does not end with '-mock'."
+          echo "Error: The provided version does not end with '-mock.'"
+          exit 1
+        fi
 
     - name: Delete release if the provided version ends with "-mock"
       id: delete_version
